language: objective-c
xcode_project: MBToolbox.xcodeproj
osx_image: xcode8

git:
  depth: 1
  submodules: false

before_install:
  git submodule update --init

install:
  gem install xcpretty

script:
- set -o pipefail && xcodebuild -project MBToolbox.xcodeproj -scheme 'MBToolbox-iOS' -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 7' clean build
# | xcpretty
- set -o pipefail && xcodebuild -project MBToolbox.xcodeproj -scheme 'MBToolbox-iOS' -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 7' test
# | xcpretty
- set -o pipefail && xcodebuild -project MBToolbox.xcodeproj -scheme 'MBToolbox-macOS' -destination 'platform=macOS' clean build
# | xcpretty
- set -o pipefail && xcodebuild -project MBToolbox.xcodeproj -scheme 'MBToolbox-macOS' -destination 'platform=macOS' test
# | xcpretty
